services:
  reverse_proxy:
    image: drmendel/hera_spice_3d_space:latest
    container_name: reverse_proxy
    restart: unless-stopped
    environment:
      - DOMAIN_NAME=localhost                       # Domain name or public IP
    volumes:
      - ./ssl/key.pem:/etc/nginx/ssl/key.pem:ro     # SSL private key (host path → container path)
      - ./ssl/cert.pem:/etc/nginx/ssl/cert.pem:ro   # SSL certificate (host path → container path)
      #- ./nginx.conf:/etc/nginx/nginx.conf.tmp      # Custom nginx config (host path → container path) (optional)
    ports:
      - "80:80"     # HTTP
      - "443:443"   # HTTPS
    networks:
      - app_net
    depends_on:
      - backend
      - frontend

  frontend:
    image: drmendel/hera_spice_3d_client:latest
    container_name: frontend
    restart: unless-stopped
    environment:
      - PORT=80           # Change if using a custom nginx config
    networks:
      - app_net

  backend:
    image: drmendel/hera_spice_ws_server:latest
    container_name: backend
    restart: unless-stopped
    volumes:
      - ./data:/data:rw  # Local folder for storing SPICE kernel data (host path → container path)
    environment:
      - PORT=80             # Change if using a custom nginx config (optional)
      - SYNC_INTERVAL=3600  # Spice kernel syncronization interval in seconds (optional)
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
